<?php

/**
 * @file
 * Defines a new shipping method with mondial relay service
 */

/**
 * Implements hook_permission().
 *
 */
function commerce_mondial_relay_permission() {
  return array(
    'administer commerce mondial relay' =>  array(
      'title' => t('Administer module commerce mondial relay'),
      'description' => t('Administer module commerce mondial relay'),
    ),
  );

}

/**
 * Implements hook_menu().
 *
 */
function commerce_mondial_relay_menu() {
  $items['admin/config/system/mondialrelay'] = array(
    'title' => 'Administer module commerce mondial relay',
    'description' => 'Administer module commerce mondial relay',
    'page callback' => 'commerce_mondial_relay_page_config',
    'access arguments' => array('administer commerce mondial relay'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


function commerce_mondial_relay_preprocess_page(&$vars, $hook) {
    drupal_add_js('http://widget.mondialrelay.com/scripts/jquery-1.6.2.min.js', 'external');
    drupal_add_js('http://maps.googleapis.com/maps/api/js?&sensor=false', 'external');
    drupal_add_js('http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble-compiled.js', 'external');
    drupal_add_js('http://widget.mondialrelay.com/pr_find/pr_find_gmaps3.js', 'external');
    drupal_add_js(drupal_get_path('module', 'commerce_mondial_relay','footer') .'/js/cmr.js', 'file');
    $vars['scripts'] = drupal_get_js();

    drupal_add_css(drupal_get_path('module', 'commerce_mondial_relay') . '/css/cmr.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}

function commerce_mondial_relay_page_config(){
  $block = block_load('commerce_mondial_relay','cmr_widget');
  $renderable_block =  _block_get_renderable_array(_block_render_blocks(array($block)));

  return array(
    "#markup" =>'<div>
                    Point relais : <div id="Retour_Display">Aucun</div>
                    <div id="Zone_Widget"></div>
                </div>'
      .drupal_render(drupal_get_form('commerce_mondial_relay_getdetailrelay_form')),
  );
  //return drupal_get_form('commerce_mondial_relay_config_form');
}

function commerce_mondial_relay_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form_id);
  if($form_id == 'commerce_mondial_relay_getdetailrelay_form') {
    //$form['#validate'][] = 'commerce_mondial_relay_getdetailrelay_form_validate';
    //$form['#submit'][] = 'commerce_mondial_relay_getdetailrelay_form_submit';
  }
}

function commerce_mondial_relay_getdetailrelay_form_validate($form, &$form_state) {
  if(empty($form_state['input']['prid'])){
    form_set_error('prid', 'PRID vide');
  }
}

function commerce_mondial_relay_getdetailrelay_form_submit($form, &$form_state) {
  // submit here
}

function commerce_mondial_relay_getdetailrelay_form(){
  $form =  array();

  $form['prid'] = array(
    '#type' => 'hidden',
    '#attributes' => array(
      'id' => array('Retour_Widget'),
    ),
    '#value' => '',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#disabled' => TRUE,
    '#description' => t('Select a mondial relay point and click on this button'),
    '#value' => t('Next step'),
  );

  return $form;
}

function commerce_mondial_relay_config_form(){
  $form =  array();

  return $form;
}

function commerce_mondial_relay_config_form_validate($form,&$form_state){
}

function commerce_mondial_relay_config_form_submit($form,&$form_state){
}
